

PRAGMA foreign_keys = OFF;
DROP TABLE IF EXISTS A;
DROP TABLE IF EXISTS B;

	PRAGMA foreign_keys = ON;
			
	CREATE TABLE A(
		a INT PRIMARY KEY,
		FOREIGN KEY(a) REFERENCES B(b) DEFERRABLE INITIALLY DEFERRED
	);

	CREATE TABLE B(
		b INT PRIMARY KEY , 
		FOREIGN KEY(b) REFERENCES A(a)  DEFERRABLE INITIALLY DEFERRED
	);
	
	
	BEGIN TRANSACTION;
	INSERT INTO A VALUES (1);
	INSERT INTO B VALUES (1);
	END  TRANSACTION;


	
	SELECT * FROM A;
	SELECT * FROM B;
	
	
	
	

